services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: innowise/internship/user-service
    container_name: user-service
    ports:
      - '8081:8080'
    depends_on:
      - postgres
      - redis
    networks:
      - backend-net
      - user-service-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECONDARY_PROFILE=dev
      - APP_LOGGING_LEVEL=debug
      - DB_HOST=user-service-postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=user-service-redis
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  postgres:
    image: postgres:15
    container_name: user-service-postgres
    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data
    networks:
      - user-service-net
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:7
    container_name: user-service-redis
    volumes:
      - user-service-redis-data:/data
    networks:
      - user-service-net
    command: redis-server --appendonly yes

volumes:
  user-service-postgres-data: {}
  user-service-redis-data: {}

networks:
  backend-net:
    external: true
  user-service-net:
    driver: bridge