spring:
  profiles:
    active: local
    include: ${SPRING_SECONDARY_PROFILE:prod}
  application:
    name: user-service
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
  jpa:
    open-in-view: false
  cache:
    type: redis
  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
eureka:
  instance:
    metadata-map:
      grpc.port: 9090